version: 2.1

orbs:
  telemetry_metrics_statsd:
    executors:
      elixir:
        parameters:
          elixir:
            description: Elixir version to used by the job
            type: string
          otp:
            description: OTP release to used by the job
            type: string
        docker:
          - image: arkgil/alpine-elixir:<<parameters.elixir>>-otp-<<parameters.otp>>

    jobs:
      build_and_test:
        parameters:
          elixir:
            description: Elixir version to used by the job
            type: string
          otp:
            description: OTP release to used by the job
            type: string
          check_format:
            description: Verify source code format with `mix format`
            type: boolean
            default: false
        executor:
          name: elixir
          elixir: <<parameters.elixir>>
          otp: <<parameters.otp>>
        steps:
          - run: mix local.hex --force
          - run: mix local.rebar --force
          - checkout
          - restore_cache:
              keys:
                - dialyzer-PLT-<<parameters.elixir>>-<<parameters.otp>>-{{ checksum "mix.lock" }}
                - dialyzer-PLT-<<parameters.elixir>>-<<parameters.otp>>
          - restore_cache:
              keys:
                - deps-<<parameters.elixir>>-<<parameters.otp>>-{{ checksum "mix.lock" }}
                - deps-<<parameters.elixir>>-<<parameters.otp>>
          - run: mix deps.get
          - run: make test
          - when:
              condition: << parameters.check_format >>
              steps:
                - run: mix format --check-formatted
          - run: mix dialyzer --halt-exit-status
          - save_cache:
              key: dialyzer-PLT-<<parameters.elixir>>-<<parameters.otp>>-{{ checksum "mix.lock" }}
              paths:
              - _build
          - save_cache:
              key: deps-<<parameters.elixir>>-<<parameters.otp>>-{{ checksum "mix.lock" }}
              paths:
              - deps

workflows:
  build_and_test:
    jobs:
      - telemetry_metrics_statsd/build_and_test:
          name: "1.11-otp-23"
          elixir: "1.11.0"
          otp: "23"
          check_format: true
      - telemetry_metrics_statsd/build_and_test:
          name: "1.11-otp-21"
          elixir: "1.11.0"
          otp: "21"
      - telemetry_metrics_statsd/build_and_test:
          name: "1.7-otp-22"
          elixir: "1.7.4"
          otp: "22"
      - telemetry_metrics_statsd/build_and_test:
          name: "1.7-otp-19"
          elixir: "1.7.4"
          otp: "19"
